# Generated by Django 4.1.4 on 2023-07-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('author', models.CharField(max_length=126)),
                ('publish_date', models.DateTimeField(verbose_name='Publish date')),
            ],
        ),
    ]
